"""Resolving when an event was first recorded, for /just-added/.

The join is the fragile part. Event identity is not consistent across the two
sides — iCal events share a guid with the site's data, submitted events do not
(next_dctech_events-p8o) — so there are two lookups, and `_title_key` has to
stay byte-identical in three places: here, the site exporter, and
updates_publisher. These tests pin the precedence and the key format.
"""
import json

import pytest

from calgen.added_at import (
    _title_key, added_at, added_on, get_added_at_index, group_by_added_date,
)


def _write_index(root, by_guid=None, by_title=None):
    d = root / '_data'
    d.mkdir(exist_ok=True)
    (d / 'added_at.json').write_text(json.dumps(
        {'by_guid': by_guid or {}, 'by_title': by_title or {}}))


def _event(title='Meetup', date='2026-09-01', guid=None, time='18:30'):
    e = {'title': title, 'date': date, 'time': time}
    if guid:
        e['guid'] = guid
    return e


@pytest.fixture
def site(tmp_path, monkeypatch):
    monkeypatch.chdir(tmp_path)
    return tmp_path


class TestTitleKey:
    def test_shape(self):
        assert _title_key('2026-09-01', 'Open Hack') == '2026-09-01|open hack'

    def test_case_and_whitespace_are_normalized(self):
        assert _title_key('2026-09-01', '  Open   HACK ') == _title_key('2026-09-01', 'Open Hack')

    def test_none_title_does_not_raise(self):
        assert _title_key('2026-09-01', None) == '2026-09-01|'


class TestIndexLoading:
    def test_missing_file_is_empty_not_an_error(self, site):
        assert get_added_at_index() == ({}, {})

    def test_malformed_json_is_empty_not_an_error(self, site):
        d = site / '_data'
        d.mkdir()
        (d / 'added_at.json').write_text('{[not json')
        assert get_added_at_index() == ({}, {})

    def test_loads_both_halves(self, site):
        _write_index(site, {'g1': '2026-08-01T00:00:00Z'}, {'k': '2026-08-02T00:00:00Z'})
        assert get_added_at_index() == (
            {'g1': '2026-08-01T00:00:00Z'}, {'k': '2026-08-02T00:00:00Z'})


class TestResolution:
    def test_guid_match(self):
        e = _event(guid='g1')
        assert added_at(e, {'g1': '2026-08-01T09:00:00Z'}, {}) == '2026-08-01T09:00:00Z'

    def test_title_fallback_when_guid_is_absent_from_the_index(self):
        """Submitted events are keyed EVENT#<8 hex> in the table but carry a
        recomputed 32-char hash on the site, so the guid never matches."""
        e = _event(title='District Arcade', date='2026-11-14', guid='recomputed-hash')
        by_title = {'2026-11-14|district arcade': '2026-08-08T12:53:38Z'}
        assert added_at(e, {}, by_title) == '2026-08-08T12:53:38Z'

    def test_guid_wins_over_a_title_collision(self):
        e = _event(title='Standup', date='2026-09-01', guid='g1')
        got = added_at(e, {'g1': '2026-08-06T00:00:00Z'},
                       {'2026-09-01|standup': '2026-01-01T00:00:00Z'})
        assert got == '2026-08-06T00:00:00Z'

    def test_unknown_event_resolves_to_none(self):
        assert added_at(_event(guid='nope'), {}, {}) is None

    def test_added_on_truncates_to_the_date(self):
        e = _event(guid='g1')
        assert added_on(e, {'g1': '2026-08-13T23:59:59Z'}, {}) == '2026-08-13'

    def test_added_on_of_an_unknown_event_is_none(self):
        assert added_on(_event(guid='nope'), {}, {}) is None


class TestGrouping:
    def test_no_index_yields_no_days(self, site):
        assert group_by_added_date([_event(guid='g1')]) == []

    def test_groups_by_day_newest_first(self, site):
        _write_index(site, {
            'a': '2026-08-10T09:00:00Z',
            'b': '2026-08-12T09:00:00Z',
            'c': '2026-08-12T18:00:00Z',
        })
        days = group_by_added_date([
            _event('A', guid='a'), _event('B', guid='b'), _event('C', guid='c')])
        assert [d['date'] for d in days] == ['2026-08-12', '2026-08-10']
        assert [d['count'] for d in days] == [2, 1]

    def test_events_with_no_recorded_date_are_omitted(self, site):
        """Recurring occurrences are generated by calgen and have no EVENT#
        row, so 'unknown' is common and must not become a bogus bucket."""
        _write_index(site, {'a': '2026-08-10T09:00:00Z'})
        days = group_by_added_date([_event('Known', guid='a'), _event('Recurring', guid='x')])
        assert [e['title'] for d in days for e in d['events']] == ['Known']

    def test_limit_days_caps_days_not_events(self, site):
        _write_index(site, {f'g{i}': f'2026-08-{10 + i:02d}T09:00:00Z' for i in range(5)})
        days = group_by_added_date(
            [_event(f'E{i}', guid=f'g{i}') for i in range(5)], limit_days=2)
        assert [d['date'] for d in days] == ['2026-08-14', '2026-08-13']

    def test_events_within_a_day_sort_by_event_date_then_time(self, site):
        _write_index(site, {g: '2026-08-10T09:00:00Z' for g in ('a', 'b', 'c')})
        days = group_by_added_date([
            _event('Late', date='2026-09-02', time='19:00', guid='a'),
            _event('Early', date='2026-09-02', time='08:00', guid='b'),
            _event('First', date='2026-09-01', time='20:00', guid='c'),
        ])
        assert [e['title'] for e in days[0]['events']] == ['First', 'Early', 'Late']

    def test_anchor_matches_the_date_for_stable_deep_links(self, site):
        _write_index(site, {'a': '2026-08-10T09:00:00Z'})
        day = group_by_added_date([_event(guid='a')])[0]
        assert day['anchor'] == day['date'] == '2026-08-10'
