"""Publish the weekly /updates post: everything added to the calendar this week.

Runs Wednesday morning. Snapshots every event *added* in the previous seven
days into a single `UPDATE#{publish_date}` DynamoDB item; the table's stream
then triggers the usual debounced site rebuild, which renders
/updates/<y>/<m>/<d>/ within ~90s.

Why a snapshot instead of rendering the post live: calgen's pipeline and
`get_events()` both drop events dated before today, so a post rendered from
live data would empty out as the events it announced happened. Freezing the
listing at publish time is what makes the archive permanent.

Two sources, each answering the question it is authoritative for:

* **What is on the calendar** comes from the site's own published events.json.
  That file is exactly the set of events the site is showing, so a post can
  never announce something a reader cannot find — and, more to the point,
  anything still sitting in the moderation queue is a DRAFT# item that has
  never been published, so it cannot leak into a post by construction.
* **When it was added** comes from the `createdAt` on the table's EVENT#
  items, which is the only place that is recorded.

Joining those two is not quite trivial: iCal events share one guid across both
(the aggregator computes it and stores it as the key), but *submitted* events
are keyed `EVENT#<8 hex>` while calgen recomputes a 32-char content hash for
them — see next_dctech_events-p8o. Until that is fixed the join falls back to
matching on (date, title), which those events do agree on.

Consequences of sourcing from events.json worth knowing:

* An event added this week whose date has already passed is not listed. It is
  not on the calendar any more, so announcing it would be a dead link to a
  reader.
* Recurring series are not listed. Their occurrences are generated by calgen
  and have no EVENT# row, so there is no record of when they were added.
"""
import json
import os
import urllib.request
from datetime import datetime, timedelta, timezone

import boto3
from botocore.exceptions import ClientError

TABLE_NAME = os.environ["DYNAMODB_TABLE_NAME"]
EVENTS_URL = os.environ.get("EVENTS_URL", "https://dctech.events/events.json")

# How far back a post reaches. Windows are date-aligned and half-open —
# [publish_date - 7, publish_date) — so consecutive Wednesdays tile the
# calendar exactly: nothing is announced twice, nothing falls between posts.
WINDOW_DAYS = 7

# Fields worth freezing; anything else is presentation the templates re-derive.
SNAPSHOT_FIELDS = (
    "title", "date", "time", "url", "group", "group_website",
    "location", "categories", "is_recurring",
)

_dynamodb = boto3.resource("dynamodb")


def _window(publish_date):
    """The half-open [start, end) range of days a post covers."""
    return publish_date - timedelta(days=WINDOW_DAYS), publish_date


def _week_id(day):
    iso_year, iso_week, _ = day.isocalendar()
    return f"{iso_year}-W{iso_week:02d}"


def _fetch_events():
    req = urllib.request.Request(
        EVENTS_URL, headers={"User-Agent": "dctech-events-updates-publisher"}
    )
    with urllib.request.urlopen(req, timeout=30) as resp:  # nosec B310
        return json.loads(resp.read().decode("utf-8"))


def _title_key(date_str, title):
    return f"{date_str}|{' '.join(str(title or '').split()).casefold()}"


def _added_at_index(table):
    """Two lookups into the same answer: guid -> createdAt, (date, title) -> createdAt.

    The second exists only because submitted events do not share a guid with
    their events.json entry (next_dctech_events-p8o). Where both hit, the guid
    wins.
    """
    by_guid, by_title = {}, {}
    kwargs = {
        "FilterExpression": "begins_with(PK, :p) AND SK = :sk",
        "ExpressionAttributeValues": {":p": "EVENT#", ":sk": "META"},
        # `date` is a DynamoDB reserved word, hence the alias.
        "ProjectionExpression": "PK, createdAt, #d, title",
        "ExpressionAttributeNames": {"#d": "date"},
    }
    while True:
        resp = table.scan(**kwargs)
        for item in resp.get("Items", []):
            created = item.get("createdAt")
            if not created:
                continue
            by_guid[str(item["PK"]).split("#", 1)[1]] = created
            if item.get("date") and item.get("title"):
                # Keep the earliest: a duplicate row for the same listing
                # should not make an old event look newly added.
                key = _title_key(item["date"], item["title"])
                if created < by_title.get(key, created + "z"):
                    by_title[key] = created
        if "LastEvaluatedKey" not in resp:
            return by_guid, by_title
        kwargs["ExclusiveStartKey"] = resp["LastEvaluatedKey"]


def _added_at(event, by_guid, by_title):
    guid = event.get("guid")
    if guid and guid in by_guid:
        return by_guid[guid]
    return by_title.get(_title_key(event.get("date"), event.get("title")))


def _events_added_in_window(events, by_guid, by_title, start, end):
    """Events the site is showing that were added within [start, end).

    `createdAt` is an ISO-8601 UTC timestamp, so comparing it against bare
    YYYY-MM-DD bounds as strings is a correct day comparison — '...T00:27:22Z'
    sorts after its own date and before the next one.
    """
    lower, upper = start.strftime("%Y-%m-%d"), end.strftime("%Y-%m-%d")

    selected = []
    for event in events:
        added = _added_at(event, by_guid, by_title)
        if not added or not (lower <= added < upper):
            continue
        selected.append({k: event[k] for k in SNAPSHOT_FIELDS if event.get(k)})

    selected.sort(key=lambda e: (e.get("date", ""), e.get("time") or ""))
    return selected


def _next_week_bounds(publish_date):
    """Monday and Sunday of the ISO week *after* the one containing publish_date."""
    monday_this_week = publish_date - timedelta(days=publish_date.weekday())
    monday = monday_this_week + timedelta(days=7)
    return monday, monday + timedelta(days=6)


def _events_in_week(all_events, monday, sunday):
    """Snapshot of what the calendar shows for one ISO week.

    Companion to _events_added_in_window: that one answers "what is new",
    this one answers "what is on", which is what the archived /week/ page
    needs once those events have happened and dropped out of events.json.
    """
    lower, upper = monday.strftime("%Y-%m-%d"), sunday.strftime("%Y-%m-%d")
    selected = [
        {k: event[k] for k in SNAPSHOT_FIELDS if event.get(k)}
        for event in all_events
        if event.get("date") and lower <= event["date"] <= upper
    ]
    selected.sort(key=lambda e: (e.get("date", ""), e.get("time") or ""))
    return selected


def _archive_item(all_events, publish_date, today):
    """The ARCHIVE# row for the week after publish_date, or None to skip it.

    Guarded against `today`, not `publish_date`, and that distinction is the
    whole point. Targeting the week after publish_date always lands in the
    future on a normal Wednesday run — but the handler accepts a
    `published_on` override for re-running an old post, and under that
    override the target week can already be over. events.json only ever
    holds upcoming events, so capturing a finished week yields an empty or
    truncated list, and writing it would destroy a good capture rather than
    refresh it. Skipping is the only safe answer.
    """
    monday, sunday = _next_week_bounds(publish_date)
    if monday <= today:
        return None
    events = _events_in_week(all_events, monday, sunday)
    return {
        "PK": f"ARCHIVE#{_week_id(monday)}",
        # SK=META keeps this inside the site exporter's existing scan.
        "SK": "META",
        "week_id": _week_id(monday),
        "week_start": monday.strftime("%Y-%m-%d"),
        "week_end": sunday.strftime("%Y-%m-%d"),
        "captured_at": datetime.now(timezone.utc)
                               .isoformat(timespec="seconds")
                               .replace("+00:00", "Z"),
        "event_count": len(events),
        "events": events,
    }


def _summarize(events, start, last_day, max_titles=3):
    """The blurb calgen shows on /updates and in the feed."""
    span = f"{start.strftime('%B %-d')}–{last_day.strftime('%-d')}"
    if start.month != last_day.month:
        span = f"{start.strftime('%B %-d')}–{last_day.strftime('%B %-d')}"

    count = len(events)
    if not count:
        return f"No new events were added between {span}."

    titles = [e["title"] for e in events if e.get("title")][:max_titles]
    blurb = ", ".join(titles)
    remaining = count - len(titles)
    if remaining > 0:
        blurb += f", and {remaining} more"
    plural = "s" if count != 1 else ""
    return f"{count} event{plural} added between {span}: {blurb}."


def lambda_handler(event, context):
    event = event or {}
    publish_date = datetime.now(timezone.utc).date()
    if event.get("published_on"):
        publish_date = datetime.strptime(event["published_on"], "%Y-%m-%d").date()

    start, end = _window(publish_date)
    last_day = end - timedelta(days=1)

    all_events = _fetch_events()
    table = _dynamodb.Table(TABLE_NAME)
    by_guid, by_title = _added_at_index(table)
    new_events = _events_added_in_window(all_events, by_guid, by_title, start, end)

    item = {
        "PK": f"UPDATE#{publish_date:%Y-%m-%d}",
        # SK=META keeps the item inside the site exporter's existing
        # `SK == META` scan, so no export-side filter has to change.
        "SK": "META",
        # The ISO week of publication, which is what /week/ links to. Older
        # posts used it as their key, back when a post *was* a week.
        "week_id": _week_id(publish_date),
        "published_on": publish_date.strftime("%Y-%m-%d"),
        # calgen files a roundup under week_start; keeping it equal to the
        # publication date is what puts this post at /updates/<y>/<m>/<d>/.
        "week_start": publish_date.strftime("%Y-%m-%d"),
        "added_since": start.strftime("%Y-%m-%d"),
        "added_until": last_day.strftime("%Y-%m-%d"),
        "title": (
            f"New on DC Tech Events: week of {start.strftime('%B %-d, %Y')}"
        ),
        "summary": _summarize(new_events, start, last_day),
        "published_at": datetime.now(timezone.utc)
                                .isoformat(timespec="seconds")
                                .replace("+00:00", "Z"),
        "event_count": len(new_events),
        "events": new_events,
    }

    archive = _archive_item(all_events, publish_date,
                            datetime.now(timezone.utc).date())

    if event.get("dry_run"):
        print(json.dumps(item, indent=2))
        if archive:
            print(json.dumps(archive, indent=2))
        return {"status": "dry_run", "item": item, "archive": archive}

    # Written before the post, and unconditionally. The archive is a capture
    # of a week still in the future, so a re-run only ever replaces it with a
    # fresher capture of the same week; doing it first means a retry after a
    # partial failure re-does both in a consistent order.
    if archive:
        _dynamodb.Table(TABLE_NAME).put_item(Item=archive)
        print(f"Archived {archive['PK']} with {archive['event_count']} events.")

    try:
        # Never silently rewrite a published post: the archive is supposed to
        # be a record of what was new that week. `force` exists for manual
        # correction of a bad run.
        kwargs = {} if event.get("force") else {
            "ConditionExpression": "attribute_not_exists(PK)"
        }
        table.put_item(Item=item, **kwargs)
    except ClientError as exc:
        if exc.response["Error"]["Code"] == "ConditionalCheckFailedException":
            print(f"Post for {publish_date} already published; leaving it alone.")
            return {"published_on": item["published_on"],
                    "status": "already_published"}
        raise

    print(f"Published {item['PK']} with {len(new_events)} events.")
    return {
        "published_on": item["published_on"],
        "status": "published",
        "event_count": len(new_events),
    }
