"""Tests for the weekly /updates publisher.

Run: DYNAMODB_TABLE_NAME=t python -m pytest test_app.py
"""
import os
from datetime import date, timedelta

import pytest

os.environ.setdefault("DYNAMODB_TABLE_NAME", "test-table")

import app  # noqa: E402

WEEK = (date(2026, 8, 5), date(2026, 8, 12))  # a Wednesday-to-Wednesday window


def added(events, by_guid=None, by_title=None, window=WEEK):
    """Titles selected from `events`, newest window by default."""
    selected = app._events_added_in_window(
        events, by_guid or {}, by_title or {}, *window
    )
    return [e["title"] for e in selected]


def test_window_is_seven_days_back_from_publication():
    start, end = app._window(date(2026, 8, 12))
    assert (start, end) == (date(2026, 8, 5), date(2026, 8, 12))
    assert (end - start).days == app.WINDOW_DAYS


def test_consecutive_windows_tile_without_gap_or_overlap():
    _, first_end = app._window(date(2026, 8, 12))
    second_start, _ = app._window(date(2026, 8, 19))
    assert first_end == second_start


def test_week_id_matches_calgen_format():
    assert app._week_id(date(2026, 8, 12)) == "2026-W33"
    # Zero-padded, so it round-trips through calgen's parse_week_identifier.
    assert app._week_id(date(2026, 1, 7)) == "2026-W02"


def test_iso_year_rollover_uses_iso_year_not_calendar_year():
    # 2025-12-31 is a Wednesday in ISO week 2026-W01.
    assert app._week_id(date(2025, 12, 31)) == "2026-W01"


def test_selects_only_events_added_inside_the_window():
    events = [
        {"title": "Too old", "date": "2026-09-01", "guid": "a"},
        {"title": "First day", "date": "2026-09-02", "guid": "b"},
        {"title": "Last day", "date": "2026-09-03", "guid": "c"},
        {"title": "Publication day", "date": "2026-09-04", "guid": "d"},
    ]
    by_guid = {
        "a": "2026-08-04T23:59:59Z",
        "b": "2026-08-05T00:00:00Z",
        "c": "2026-08-11T23:59:59Z",
        # Added the morning of the post; belongs to next week's window.
        "d": "2026-08-12T09:00:00Z",
    }
    assert added(events, by_guid) == ["First day", "Last day"]


def test_event_with_no_recorded_added_time_is_left_out():
    # Recurring occurrences are generated by calgen and have no EVENT# row.
    events = [{"title": "Recurring", "date": "2026-08-20", "guid": "x"}]
    assert added(events) == []


def test_submitted_events_fall_back_to_date_and_title():
    # Submitted events are keyed EVENT#<8 hex> but appear in events.json under
    # a recomputed 32-char hash, so the guid never matches (…-p8o).
    events = [{"title": "District Arcade", "date": "2026-11-14",
               "guid": "6832a1cd9f0e4b1a8c7d2e5f0a1b2c3d"}]
    by_title = {"2026-11-14|district arcade": "2026-08-08T12:53:38Z"}
    assert added(events, by_title=by_title) == ["District Arcade"]


def test_title_match_ignores_case_and_whitespace():
    events = [{"title": "  Open   Hack ", "date": "2026-08-24"}]
    by_title = {"2026-08-24|open hack": "2026-08-06T00:00:00Z"}
    assert added(events, by_title=by_title) == ["  Open   Hack "]


def test_guid_wins_over_a_title_collision():
    events = [{"title": "Standup", "date": "2026-08-20", "guid": "real"}]
    by_guid = {"real": "2026-08-06T00:00:00Z"}
    by_title = {"2026-08-20|standup": "2026-01-01T00:00:00Z"}
    assert added(events, by_guid, by_title) == ["Standup"]


def test_events_sorted_by_date_then_time():
    events = [
        {"title": "C", "date": "2026-09-05", "time": "09:00", "guid": "c"},
        {"title": "B", "date": "2026-08-20", "time": "19:00", "guid": "b"},
        {"title": "A", "date": "2026-08-20", "time": "08:00", "guid": "a"},
    ]
    when = {g: "2026-08-06T00:00:00Z" for g in "abc"}
    assert added(events, when) == ["A", "B", "C"]


def test_event_missing_time_sorts_without_error():
    events = [
        {"title": "Timed", "date": "2026-08-20", "time": "10:00", "guid": "a"},
        {"title": "Untimed", "date": "2026-08-20", "guid": "b"},
    ]
    when = {"a": "2026-08-06T00:00:00Z", "b": "2026-08-06T00:00:00Z"}
    assert added(events, when) == ["Untimed", "Timed"]


def test_snapshot_keeps_only_known_fields():
    events = [{
        "title": "Meetup",
        "date": "2026-08-20",
        "url": "https://example.com",
        "group": "Python DC",
        "guid": "g",
        "description": "long prose the templates re-derive",
    }]
    snapshot = app._events_added_in_window(
        events, {"g": "2026-08-06T00:00:00Z"}, {}, *WEEK
    )[0]
    assert set(snapshot) == {"title", "date", "url", "group"}


def test_added_index_keeps_the_earliest_time_for_a_repeated_listing():
    scanned = [
        {"PK": "EVENT#new", "createdAt": "2026-08-06T00:00:00Z",
         "date": "2026-08-20", "title": "Repeat"},
        {"PK": "EVENT#old", "createdAt": "2026-02-01T00:00:00Z",
         "date": "2026-08-20", "title": "Repeat"},
    ]
    by_guid, by_title = app._added_at_index(_FakeTable(scanned))
    assert by_title["2026-08-20|repeat"] == "2026-02-01T00:00:00Z"
    assert by_guid == {"new": "2026-08-06T00:00:00Z",
                       "old": "2026-02-01T00:00:00Z"}


def test_added_index_follows_scan_pagination():
    pages = [
        {"Items": [{"PK": "EVENT#a", "createdAt": "2026-08-06T00:00:00Z"}],
         "LastEvaluatedKey": {"PK": "EVENT#a"}},
        {"Items": [{"PK": "EVENT#b", "createdAt": "2026-08-07T00:00:00Z"}]},
    ]
    by_guid, _ = app._added_at_index(_FakePagedTable(pages))
    assert set(by_guid) == {"a", "b"}


def test_added_index_skips_rows_with_no_created_at():
    by_guid, by_title = app._added_at_index(
        _FakeTable([{"PK": "EVENT#a", "date": "2026-08-20", "title": "X"}])
    )
    assert (by_guid, by_title) == ({}, {})


@pytest.mark.parametrize("count,expected", [
    (0, "No new events were added between August 5–11."),
    (1, "1 event added between August 5–11: E0."),
])
def test_summary_wording(count, expected):
    events = [{"title": f"E{i}"} for i in range(count)]
    got = app._summarize(events, date(2026, 8, 5), date(2026, 8, 11))
    assert got == expected


def test_summary_truncates_a_long_list():
    events = [{"title": f"E{i}"} for i in range(5)]
    got = app._summarize(events, date(2026, 8, 5), date(2026, 8, 11))
    assert got == "5 events added between August 5–11: E0, E1, E2, and 2 more."


def test_summary_spells_out_a_span_that_crosses_a_month():
    got = app._summarize([], date(2026, 7, 29), date(2026, 8, 4))
    assert got == "No new events were added between July 29–August 4."


class _FakeTable:
    def __init__(self, items):
        self._items = items

    def scan(self, **kwargs):
        return {"Items": self._items}


class _FakePagedTable:
    def __init__(self, pages):
        self._pages = pages

    def scan(self, **kwargs):
        return self._pages.pop(0)


# ── Week archive snapshots ──────────────────────────────────────────
# The publisher's second job: freeze what the calendar shows for the coming
# week, so /week/<id>/ still has content once those events have happened and
# dropped out of events.json. See calgen/archive.py for the reading side.

def scheduled(events, monday, sunday):
    return [e["title"] for e in app._events_in_week(events, monday, sunday)]


def test_next_week_bounds_are_the_following_monday_to_sunday():
    # 2026-08-12 is a Wednesday; the next ISO week runs Mon 17th – Sun 23rd.
    assert app._next_week_bounds(date(2026, 8, 12)) == (date(2026, 8, 17), date(2026, 8, 23))


def test_next_week_bounds_from_a_monday_still_looks_forward():
    assert app._next_week_bounds(date(2026, 8, 17)) == (date(2026, 8, 24), date(2026, 8, 30))


def test_next_week_bounds_from_a_sunday_still_looks_forward():
    assert app._next_week_bounds(date(2026, 8, 16)) == (date(2026, 8, 17), date(2026, 8, 23))


def test_selects_events_scheduled_in_the_week_inclusive_of_both_ends():
    events = [
        {"title": "Sunday before", "date": "2026-08-16"},
        {"title": "Monday", "date": "2026-08-17"},
        {"title": "Sunday", "date": "2026-08-23"},
        {"title": "Monday after", "date": "2026-08-24"},
    ]
    assert scheduled(events, date(2026, 8, 17), date(2026, 8, 23)) == ["Monday", "Sunday"]


def test_scheduled_events_are_sorted_by_date_then_time():
    events = [
        {"title": "Later", "date": "2026-08-19", "time": "19:00"},
        {"title": "Earlier", "date": "2026-08-19", "time": "09:00"},
        {"title": "First", "date": "2026-08-17"},
    ]
    assert scheduled(events, date(2026, 8, 17), date(2026, 8, 23)) == [
        "First", "Earlier", "Later"]


def test_scheduled_snapshot_keeps_only_known_fields():
    events = [{
        "title": "Meetup", "date": "2026-08-18", "time": "18:30",
        "url": "https://example.org/e", "group": "DC Python",
        "location": "Washington, DC", "categories": ["python"],
        "guid": "drop-me", "region": "dc", "source": "ical",
    }]
    snap = app._events_in_week(events, date(2026, 8, 17), date(2026, 8, 23))[0]
    assert set(snap) <= set(app.SNAPSHOT_FIELDS)
    assert "guid" not in snap and "region" not in snap


def test_event_without_a_date_is_skipped_rather_than_raising():
    events = [{"title": "Undated"}, {"title": "Dated", "date": "2026-08-18"}]
    assert scheduled(events, date(2026, 8, 17), date(2026, 8, 23)) == ["Dated"]


def test_archive_item_is_keyed_and_bounded_by_the_coming_week():
    events = [{"title": "Meetup", "date": "2026-08-18"}]
    item = app._archive_item(events, date(2026, 8, 12), date(2026, 8, 12))
    assert item["PK"] == "ARCHIVE#2026-W34"
    assert item["SK"] == "META"
    assert (item["week_start"], item["week_end"]) == ("2026-08-17", "2026-08-23")
    assert item["event_count"] == 1


def test_archive_item_is_written_even_when_the_week_is_empty():
    """An empty week is a fact worth recording — it is what stops the page
    from 404ing, and it distinguishes 'nothing on' from 'never captured'."""
    item = app._archive_item([], date(2026, 8, 12), date(2026, 8, 12))
    assert item is not None
    assert item["event_count"] == 0
    assert item["events"] == []


def test_backdated_rerun_does_not_overwrite_a_finished_week():
    """A manual re-run passes `published_on`, which can point at a week that
    is already over. events.json holds only upcoming events, so capturing it
    now would write an empty list over a good capture."""
    publish, today = date(2026, 8, 12), date(2026, 9, 30)
    assert app._archive_item([], publish, today) is None


def test_no_archive_once_the_target_week_has_started():
    publish = date(2026, 8, 12)          # targets Mon 2026-08-17
    assert app._archive_item([], publish, date(2026, 8, 17)) is None   # first day
    assert app._archive_item([], publish, date(2026, 8, 20)) is None   # mid-week
    assert app._archive_item([], publish, date(2026, 8, 16)) is not None  # day before


def test_consecutive_wednesday_runs_archive_consecutive_weeks():
    """No week may be skipped: a gap is a permanently missing archive."""
    weeks = [app._archive_item([], d, d)["week_id"]
             for d in (date(2026, 8, 12) + timedelta(days=7 * i) for i in range(4))]
    assert weeks == ["2026-W34", "2026-W35", "2026-W36", "2026-W37"]
