"""Tests for the weekly /updates publisher.

Run: DYNAMODB_TABLE_NAME=t python -m pytest test_app.py
"""
import os
from datetime import date, timedelta

import pytest

os.environ.setdefault("DYNAMODB_TABLE_NAME", "test-table")

import app  # noqa: E402

WEEK = (date(2026, 8, 5), date(2026, 8, 12))  # a Wednesday-to-Wednesday window


def added(events, by_guid=None, by_title=None, window=WEEK):
    """Titles selected from `events`, newest window by default."""
    selected = app._events_added_in_window(
        events, by_guid or {}, by_title or {}, *window
    )
    return [e["title"] for e in selected]


def test_window_is_seven_days_back_from_publication():
    start, end = app._window(date(2026, 8, 12))
    assert (start, end) == (date(2026, 8, 5), date(2026, 8, 12))
    assert (end - start).days == app.WINDOW_DAYS


def test_consecutive_windows_tile_without_gap_or_overlap():
    _, first_end = app._window(date(2026, 8, 12))
    second_start, _ = app._window(date(2026, 8, 19))
    assert first_end == second_start


def test_week_id_matches_calgen_format():
    assert app._week_id(date(2026, 8, 12)) == "2026-W33"
    # Zero-padded, so it round-trips through calgen's parse_week_identifier.
    assert app._week_id(date(2026, 1, 7)) == "2026-W02"


def test_iso_year_rollover_uses_iso_year_not_calendar_year():
    # 2025-12-31 is a Wednesday in ISO week 2026-W01.
    assert app._week_id(date(2025, 12, 31)) == "2026-W01"


def test_selects_only_events_added_inside_the_window():
    events = [
        {"title": "Too old", "date": "2026-09-01", "guid": "a"},
        {"title": "First day", "date": "2026-09-02", "guid": "b"},
        {"title": "Last day", "date": "2026-09-03", "guid": "c"},
        {"title": "Publication day", "date": "2026-09-04", "guid": "d"},
    ]
    by_guid = {
        "a": "2026-08-04T23:59:59Z",
        "b": "2026-08-05T00:00:00Z",
        "c": "2026-08-11T23:59:59Z",
        # Added the morning of the post; belongs to next week's window.
        "d": "2026-08-12T09:00:00Z",
    }
    assert added(events, by_guid) == ["First day", "Last day"]


def test_event_with_no_recorded_added_time_is_left_out():
    # Recurring occurrences are generated by calgen and have no EVENT# row.
    events = [{"title": "Recurring", "date": "2026-08-20", "guid": "x"}]
    assert added(events) == []


def test_submitted_events_fall_back_to_date_and_title():
    # Submitted events are keyed EVENT#<8 hex> but appear in events.json under
    # a recomputed 32-char hash, so the guid never matches (…-p8o).
    events = [{"title": "District Arcade", "date": "2026-11-14",
               "guid": "6832a1cd9f0e4b1a8c7d2e5f0a1b2c3d"}]
    by_title = {"2026-11-14|district arcade": "2026-08-08T12:53:38Z"}
    assert added(events, by_title=by_title) == ["District Arcade"]


def test_title_match_ignores_case_and_whitespace():
    events = [{"title": "  Open   Hack ", "date": "2026-08-24"}]
    by_title = {"2026-08-24|open hack": "2026-08-06T00:00:00Z"}
    assert added(events, by_title=by_title) == ["  Open   Hack "]


def test_guid_wins_over_a_title_collision():
    events = [{"title": "Standup", "date": "2026-08-20", "guid": "real"}]
    by_guid = {"real": "2026-08-06T00:00:00Z"}
    by_title = {"2026-08-20|standup": "2026-01-01T00:00:00Z"}
    assert added(events, by_guid, by_title) == ["Standup"]


def test_events_sorted_by_date_then_time():
    events = [
        {"title": "C", "date": "2026-09-05", "time": "09:00", "guid": "c"},
        {"title": "B", "date": "2026-08-20", "time": "19:00", "guid": "b"},
        {"title": "A", "date": "2026-08-20", "time": "08:00", "guid": "a"},
    ]
    when = {g: "2026-08-06T00:00:00Z" for g in "abc"}
    assert added(events, when) == ["A", "B", "C"]


def test_event_missing_time_sorts_without_error():
    events = [
        {"title": "Timed", "date": "2026-08-20", "time": "10:00", "guid": "a"},
        {"title": "Untimed", "date": "2026-08-20", "guid": "b"},
    ]
    when = {"a": "2026-08-06T00:00:00Z", "b": "2026-08-06T00:00:00Z"}
    assert added(events, when) == ["Untimed", "Timed"]


def test_snapshot_keeps_only_known_fields():
    events = [{
        "title": "Meetup",
        "date": "2026-08-20",
        "url": "https://example.com",
        "group": "Python DC",
        "guid": "g",
        "description": "long prose the templates re-derive",
    }]
    snapshot = app._events_added_in_window(
        events, {"g": "2026-08-06T00:00:00Z"}, {}, *WEEK
    )[0]
    assert set(snapshot) == {"title", "date", "url", "group"}


def test_added_index_keeps_the_earliest_time_for_a_repeated_listing():
    scanned = [
        {"PK": "EVENT#new", "createdAt": "2026-08-06T00:00:00Z",
         "date": "2026-08-20", "title": "Repeat"},
        {"PK": "EVENT#old", "createdAt": "2026-02-01T00:00:00Z",
         "date": "2026-08-20", "title": "Repeat"},
    ]
    by_guid, by_title = app._added_at_index(_FakeTable(scanned))
    assert by_title["2026-08-20|repeat"] == "2026-02-01T00:00:00Z"
    assert by_guid == {"new": "2026-08-06T00:00:00Z",
                       "old": "2026-02-01T00:00:00Z"}


def test_added_index_follows_scan_pagination():
    pages = [
        {"Items": [{"PK": "EVENT#a", "createdAt": "2026-08-06T00:00:00Z"}],
         "LastEvaluatedKey": {"PK": "EVENT#a"}},
        {"Items": [{"PK": "EVENT#b", "createdAt": "2026-08-07T00:00:00Z"}]},
    ]
    by_guid, _ = app._added_at_index(_FakePagedTable(pages))
    assert set(by_guid) == {"a", "b"}


def test_added_index_skips_rows_with_no_created_at():
    by_guid, by_title = app._added_at_index(
        _FakeTable([{"PK": "EVENT#a", "date": "2026-08-20", "title": "X"}])
    )
    assert (by_guid, by_title) == ({}, {})


@pytest.mark.parametrize("count,expected", [
    (0, "No new events were added between August 5–11."),
    (1, "1 event added between August 5–11: E0."),
])
def test_summary_wording(count, expected):
    events = [{"title": f"E{i}"} for i in range(count)]
    got = app._summarize(events, date(2026, 8, 5), date(2026, 8, 11))
    assert got == expected


def test_summary_truncates_a_long_list():
    events = [{"title": f"E{i}"} for i in range(5)]
    got = app._summarize(events, date(2026, 8, 5), date(2026, 8, 11))
    assert got == "5 events added between August 5–11: E0, E1, E2, and 2 more."


def test_summary_spells_out_a_span_that_crosses_a_month():
    got = app._summarize([], date(2026, 7, 29), date(2026, 8, 4))
    assert got == "No new events were added between July 29–August 4."


class _FakeTable:
    def __init__(self, items):
        self._items = items

    def scan(self, **kwargs):
        return {"Items": self._items}


class _FakePagedTable:
    def __init__(self, pages):
        self._pages = pages

    def scan(self, **kwargs):
        return self._pages.pop(0)


# ── Week archive snapshots ──────────────────────────────────────────
# The publisher's second job: freeze what the calendar shows for the coming
# week, so /week/<id>/ still has content once those events have happened and
# dropped out of events.json. See calgen/archive.py for the reading side.

def scheduled(events, monday, sunday):
    return [e["title"] for e in app._events_in_week(events, monday, sunday)]


def test_next_week_bounds_are_the_following_monday_to_sunday():
    # 2026-08-12 is a Wednesday; the next ISO week runs Mon 17th – Sun 23rd.
    assert app._next_week_bounds(date(2026, 8, 12)) == (date(2026, 8, 17), date(2026, 8, 23))


def test_next_week_bounds_from_a_monday_still_looks_forward():
    assert app._next_week_bounds(date(2026, 8, 17)) == (date(2026, 8, 24), date(2026, 8, 30))


def test_next_week_bounds_from_a_sunday_still_looks_forward():
    assert app._next_week_bounds(date(2026, 8, 16)) == (date(2026, 8, 17), date(2026, 8, 23))


def test_selects_events_scheduled_in_the_week_inclusive_of_both_ends():
    events = [
        {"title": "Sunday before", "date": "2026-08-16"},
        {"title": "Monday", "date": "2026-08-17"},
        {"title": "Sunday", "date": "2026-08-23"},
        {"title": "Monday after", "date": "2026-08-24"},
    ]
    assert scheduled(events, date(2026, 8, 17), date(2026, 8, 23)) == ["Monday", "Sunday"]


def test_scheduled_events_are_sorted_by_date_then_time():
    events = [
        {"title": "Later", "date": "2026-08-19", "time": "19:00"},
        {"title": "Earlier", "date": "2026-08-19", "time": "09:00"},
        {"title": "First", "date": "2026-08-17"},
    ]
    assert scheduled(events, date(2026, 8, 17), date(2026, 8, 23)) == [
        "First", "Earlier", "Later"]


def test_scheduled_snapshot_keeps_only_known_fields():
    events = [{
        "title": "Meetup", "date": "2026-08-18", "time": "18:30",
        "url": "https://example.org/e", "group": "DC Python",
        "location": "Washington, DC", "categories": ["python"],
        "guid": "drop-me", "region": "dc", "source": "ical",
    }]
    snap = app._events_in_week(events, date(2026, 8, 17), date(2026, 8, 23))[0]
    assert set(snap) <= set(app.SNAPSHOT_FIELDS)
    assert "guid" not in snap and "region" not in snap


def test_event_without_a_date_is_skipped_rather_than_raising():
    events = [{"title": "Undated"}, {"title": "Dated", "date": "2026-08-18"}]
    assert scheduled(events, date(2026, 8, 17), date(2026, 8, 23)) == ["Dated"]


def archived(stored, live, today, monday=date(2026, 8, 17),
             sunday=date(2026, 8, 23)):
    item = app._archive_item(stored, live, monday, sunday, today)
    return [e["title"] for e in item["events"]]


def test_archive_item_is_keyed_and_bounded_by_its_week():
    events = [{"title": "Meetup", "date": "2026-08-18"}]
    item = app._archive_item([], events, date(2026, 8, 17), date(2026, 8, 23),
                             date(2026, 8, 12))
    assert item["PK"] == "ARCHIVE#2026-W34"
    assert item["SK"] == "META"
    assert (item["week_start"], item["week_end"]) == ("2026-08-17", "2026-08-23")
    assert item["event_count"] == 1


def test_archive_item_is_written_even_when_the_week_is_empty():
    """An empty week is a fact worth recording — it is what stops the page
    from 404ing, and it distinguishes 'nothing on' from 'never captured'."""
    item = app._archive_item([], [], date(2026, 8, 17), date(2026, 8, 23),
                             date(2026, 8, 12))
    assert item is not None
    assert item["event_count"] == 0
    assert item["events"] == []


def test_a_run_captures_this_week_and_next():
    # Two weeks per run: next week to seed it, this week to fold in whatever
    # was added since the last merge.
    assert app._archive_weeks(date(2026, 8, 12)) == [
        (date(2026, 8, 10), date(2026, 8, 16)),
        (date(2026, 8, 17), date(2026, 8, 23)),
    ]


def test_consecutive_runs_cover_consecutive_weeks_without_a_gap():
    """No week may be skipped: a gap is a permanently missing archive."""
    seen = []
    for i in range(4):
        for monday, _ in app._archive_weeks(date(2026, 8, 12) + timedelta(days=7 * i)):
            week = app._week_id(monday)
            if week not in seen:
                seen.append(week)
    assert seen == ["2026-W33", "2026-W34", "2026-W35", "2026-W36", "2026-W37"]


# ── merging a capture instead of overwriting it ──────────────────────
# The archive accumulates: a week is merged on every run, so an event added
# after the first capture still reaches the permanent record, and an event
# that has already happened is not dropped when it leaves events.json.


STORED = [
    {"title": "Already happened", "date": "2026-08-17"},
    {"title": "Happens today", "date": "2026-08-20"},
    {"title": "Still upcoming", "date": "2026-08-22"},
]


def test_a_late_addition_reaches_the_capture():
    live = STORED + [{"title": "Added since", "date": "2026-08-22"}]
    assert "Added since" in archived(STORED, live, date(2026, 8, 20))


def test_past_events_survive_leaving_events_json():
    # events.json holds nothing before today, so the stored half is the only
    # record of the days of the week already gone. Here both 08-17 and 08-20
    # have passed and only 08-22 is still live.
    live = [{"title": "Still upcoming", "date": "2026-08-22"}]
    assert archived(STORED, live, date(2026, 8, 21)) == [
        "Already happened", "Happens today", "Still upcoming",
    ]


def test_today_is_taken_from_live_not_from_the_stored_capture():
    # The boundary is inclusive of today on the live side: today's events are
    # still in events.json, and live is the fresher of the two.
    live = [{"title": "Happens today, rescheduled", "date": "2026-08-20",
             "time": "19:00"}]
    assert archived(STORED, live, date(2026, 8, 20)) == [
        "Already happened", "Happens today, rescheduled",
    ]


def test_a_cancelled_upcoming_event_is_dropped_rather_than_resurrected():
    # The reason for splitting at today instead of taking the union: live is
    # authoritative for what is still to come, deletions included. On 08-20
    # the 08-22 listing is gone from events.json, so it is gone here too.
    assert archived(STORED, [], date(2026, 8, 20)) == ["Already happened"]


def test_an_event_cancelled_after_it_happened_stays_in_the_record():
    # Past days are read from the stored capture, which live cannot revise.
    # "What the calendar showed" is the thing being archived.
    assert archived(STORED, [], date(2026, 8, 23)) == [
        "Already happened", "Happens today", "Still upcoming",
    ]


def test_merging_a_finished_week_keeps_it_intact():
    """The failure mode the old one-shot capture had to refuse outright: a
    backdated re-run whose target week is already over. events.json holds
    nothing in that range, and a merge keeps the stored capture rather than
    writing an empty list over it."""
    item = app._archive_item(STORED, [], date(2026, 8, 17), date(2026, 8, 23),
                             date(2026, 9, 30))
    assert [e["title"] for e in item["events"]] == \
        ["Already happened", "Happens today", "Still upcoming"]
    assert item["event_count"] == 3


def test_merging_a_wholly_future_week_is_just_the_live_listing():
    live = [{"title": "Next month", "date": "2026-08-22"}]
    assert archived([], live, date(2026, 8, 12)) == ["Next month"]


def test_merged_events_stay_sorted_by_date_then_time():
    stored = [{"title": "Early", "date": "2026-08-17", "time": "09:00"}]
    live = [
        {"title": "Late in the day", "date": "2026-08-22", "time": "19:00"},
        {"title": "Earlier that day", "date": "2026-08-22", "time": "12:00"},
    ]
    assert archived(stored, live, date(2026, 8, 20)) == [
        "Early", "Earlier that day", "Late in the day",
    ]


def test_events_without_a_date_are_dropped_from_a_merge():
    stored = [{"title": "No date"}, {"title": "Dated", "date": "2026-08-17"}]
    assert archived(stored, [], date(2026, 8, 20)) == ["Dated"]


def test_refresh_reads_the_stored_capture_for_each_week():
    class _ArchiveTable:
        def __init__(self):
            self.asked = []

        def get_item(self, Key):
            self.asked.append(Key["PK"])
            return {"Item": {"events": STORED}} if Key["PK"] == "ARCHIVE#2026-W34" else {}

    table = _ArchiveTable()
    items = app._refresh_archives(table, [], date(2026, 8, 12), date(2026, 9, 30))
    assert table.asked == ["ARCHIVE#2026-W33", "ARCHIVE#2026-W34"]
    # W33 had nothing stored and nothing live; W34's capture came back intact.
    assert [i["event_count"] for i in items] == [0, 3]


# ── the Monday "week ahead" link post ────────────────────────────────


def week_ahead(events, publish_date=date(2026, 8, 31)):
    return app._week_ahead_item(events, publish_date)


ON_THIS_WEEK = [
    {"title": "Monday thing", "date": "2026-08-31", "time": "18:00"},
    {"title": "Sunday thing", "date": "2026-09-06"},
    {"title": "Next week", "date": "2026-09-07"},
    {"title": "Last week", "date": "2026-08-30"},
]


def test_this_week_bounds_from_a_monday_are_that_monday_to_sunday():
    assert app._this_week_bounds(date(2026, 8, 31)) == (
        date(2026, 8, 31), date(2026, 9, 6))


def test_this_week_bounds_from_midweek_still_gives_the_containing_week():
    # The reader is standing in this week, not the next one — the opposite of
    # _next_week_bounds, which the Wednesday archive capture uses.
    assert app._this_week_bounds(date(2026, 9, 2)) == (
        date(2026, 8, 31), date(2026, 9, 6))
    assert app._this_week_bounds(date(2026, 9, 6)) == (
        date(2026, 8, 31), date(2026, 9, 6))


def test_link_post_points_at_the_week_page_for_its_own_week():
    item = week_ahead(ON_THIS_WEEK)
    assert item["week_id"] == "2026-W36"
    assert item["link_url"] == "/week/2026-W36/"


def test_link_post_is_dated_by_its_publication_date():
    item = week_ahead(ON_THIS_WEEK)
    assert item["PK"] == "UPDATE#2026-08-31"
    assert item["published_on"] == "2026-08-31"


def test_link_post_stores_no_week_start():
    # week_start is what files a post at /updates/<y>/<m>/<d>/, and a link
    # post has no page there.
    assert "week_start" not in week_ahead(ON_THIS_WEEK)


def test_link_post_is_marked_as_one():
    assert week_ahead(ON_THIS_WEEK)["post_kind"] == "link"


def test_link_post_stores_no_listing():
    # The whole point: the events live on the page it links to, which has its
    # own ARCHIVE# capture, so freezing them here would be a second copy.
    item = week_ahead(ON_THIS_WEEK)
    assert "events" not in item
    assert item["event_count"] == 2


def test_link_post_counts_only_events_inside_its_week():
    assert week_ahead(ON_THIS_WEEK)["event_count"] == 2


def test_link_post_title_names_the_monday_not_the_publish_date():
    # A backdated re-run on a Wednesday still describes the week it covers.
    item = week_ahead(ON_THIS_WEEK, publish_date=date(2026, 9, 2))
    assert item["title"] == "DC Tech Events for the week of August 31, 2026"
    assert item["PK"] == "UPDATE#2026-09-02"


def test_link_post_summary_lists_titles_and_the_span():
    summary = week_ahead(ON_THIS_WEEK)["summary"]
    assert summary == ("2 events on the calendar for August 31–September 6: "
                       "Monday thing, Sunday thing.")


def test_link_post_summary_truncates_a_long_list():
    events = [{"title": f"Thing {n}", "date": "2026-09-01"} for n in range(6)]
    assert week_ahead(events)["summary"] == (
        "6 events on the calendar for August 31–September 6: "
        "Thing 0, Thing 1, Thing 2, and 3 more.")


def test_link_post_summary_is_singular_for_one_event():
    events = [{"title": "Only thing", "date": "2026-09-01"}]
    assert week_ahead(events)["summary"].startswith("1 event on the calendar")


def test_link_post_summary_when_the_week_is_empty():
    assert week_ahead([])["summary"] == (
        "Nothing is on the calendar for August 31–September 6 yet.")


def test_span_stays_inside_one_month_when_it_can():
    assert app._span(date(2026, 8, 5), date(2026, 8, 11)) == "August 5–11"
    assert app._span(date(2026, 8, 28), date(2026, 9, 3)) == "August 28–September 3"


def test_week_ahead_and_roundup_never_collide_on_a_key():
    # Monday and Wednesday of the same ISO week share a week_id but not a PK,
    # which is what lets both post kinds live in _updates/ side by side.
    monday = week_ahead(ON_THIS_WEEK, publish_date=date(2026, 8, 31))
    assert monday["week_id"] == app._week_id(date(2026, 9, 2))
    assert monday["PK"] != f"UPDATE#{date(2026, 9, 2):%Y-%m-%d}"


# ── write-once semantics, shared by both post kinds ──────────────────


class _RecordingTable:
    """Accepts a put, or refuses it the way DynamoDB does on a live key."""

    def __init__(self, occupied=False):
        self.occupied = occupied
        self.puts = []

    def put_item(self, **kwargs):
        self.puts.append(kwargs)
        if self.occupied and "ConditionExpression" in kwargs:
            raise app.ClientError(
                {"Error": {"Code": "ConditionalCheckFailedException",
                           "Message": "already there"}},
                "PutItem",
            )
        return {}


def test_put_post_guards_an_already_published_day():
    table = _RecordingTable(occupied=True)
    assert app._put_post(table, {"PK": "UPDATE#2026-08-31"}) == "already_published"


def test_put_post_writes_when_the_day_is_free():
    table = _RecordingTable()
    assert app._put_post(table, {"PK": "UPDATE#2026-08-31"}) == "published"
    assert "ConditionExpression" in table.puts[0]


def test_force_overwrites_a_published_post():
    table = _RecordingTable(occupied=True)
    assert app._put_post(table, {"PK": "UPDATE#2026-08-31"},
                         force=True) == "published"
    # No condition, so the occupied key does not refuse it.
    assert "ConditionExpression" not in table.puts[0]


def test_put_post_reraises_anything_that_is_not_a_key_collision():
    class _Broken:
        def put_item(self, **kwargs):
            raise app.ClientError(
                {"Error": {"Code": "ProvisionedThroughputExceededException",
                           "Message": "slow down"}}, "PutItem")

    with pytest.raises(app.ClientError):
        app._put_post(_Broken(), {"PK": "UPDATE#2026-08-31"})
