"""NextApiStack — API Lambda (backend fork) + MCP Lambda behind one REST API.

Mirrors infrastructure/lib/lambda-api-stack.ts route/authorizer layout, minus
the queue-notification/cleanup Lambdas (not part of this scope). The /mcp
resource uses an AWS_IAM authorizer (trusted agents/Lambdas only).
"""
import os

import aws_cdk as cdk
from aws_cdk import (
    aws_apigateway as apigateway,
    aws_cognito as cognito,
    aws_dynamodb as dynamodb,
    aws_iam as iam,
    aws_kms as kms,
    aws_lambda as lambda_,
    aws_logs as logs,
)
from constructs import Construct

import config

BUILD_DIR = os.path.join(os.path.dirname(__file__), "..", "build")


class NextApiStack(cdk.Stack):
    def __init__(
        self,
        scope: Construct,
        construct_id: str,
        *,
        table: dynamodb.ITable,
        user_pool: cognito.IUserPool,
        user_pool_client: cognito.IUserPoolClient,
        prefs_key: kms.Key,
        **kwargs,
    ) -> None:
        super().__init__(scope, construct_id, **kwargs)

        stage_name = "prod"

        # HMAC key backing magic-link submission tokens. Its own key rather
        # than the newsletter's: sharing one would couple this stack to
        # NextNewsletterStack, and rotating either purpose's key
        # independently is worth more than one fewer resource. prefs_key
        # (below) is the one deliberate exception — subscriber preferences
        # links are generated by NextNewsletterStack's sender_function
        # (embedded in every send) and verified here, so that purpose
        # genuinely spans both stacks and gets a construct reference
        # (owned by NextNewsletterStack, passed in via app.py) the same
        # way both stacks already share the DynamoDB table.
        self.submit_key = kms.Key(
            self,
            "NextSubmitLinkKey",
            description="HMAC key for dctech.events magic-link event submission",
            key_spec=kms.KeySpec.HMAC_512,
            key_usage=kms.KeyUsage.GENERATE_VERIFY_MAC,
            # Destroying it invalidates every outstanding submission link,
            # which is recoverable (users request a new one) but rude.
            removal_policy=cdk.RemovalPolicy.RETAIN,
        )

        common_env = {
            "DYNAMODB_TABLE_NAME": table.table_name,
            "COGNITO_USER_POOL_ID": config.USER_POOL_ID,
            "COGNITO_USER_POOL_CLIENT_ID": user_pool_client.user_pool_client_id,
            "COGNITO_DOMAIN": config.COGNITO_HOSTED_UI_DOMAIN,
            "CONTACT_LIST_NAME": config.NEWSLETTER_CONTACT_LIST,
            "NEWSLETTER_TOPIC": config.NEWSLETTER_TOPIC,
            "STAGE": stage_name,
            "SUBMIT_KEY_ID": self.submit_key.key_id,
            "PREFS_KEY_ID": prefs_key.key_id,
            "BASE_URL": config.BASE_URL,
            "FROM_EMAIL": "outbound@dctech.events",
            "REPLY_TO_EMAIL": config.NEWSLETTER_ADMIN_EMAIL,
            # Immediate per-submission notification, alongside the daily
            # queue digest in NextOpsStack.
            "ADMIN_EMAIL": config.NEWSLETTER_ADMIN_EMAIL,
            "QUEUE_URL": f"{config.BASE_URL}/edit/queue.html",
            # Referenced by literal name, not by importing the project from
            # NextSiteGeneratorStack — that stack is created after this one and
            # a cross-stack import would make the dependency circular. Same
            # convention the orchestration stack uses.
            #
            # Without this, POST /api/admin/rebuild answered 503 "Site
            # generator not configured yet" and the MCP trigger_rebuild tool
            # raised. Both went unnoticed because nothing had a button on the
            # route, and because the QC agent's call to trigger_rebuild fails
            # as an MCP error result that run_qc never inspects — the rebuild
            # happened anyway via the DynamoDB stream trigger.
            "CODEBUILD_PROJECT_NAME": f"{config.PREFIX}-site-generator",
        }

        self.api_function = lambda_.Function(
            self,
            "NextApiFunction",
            function_name=f"{config.PREFIX}-api",
            runtime=lambda_.Runtime.PYTHON_3_12,
            architecture=lambda_.Architecture.X86_64,
            handler="handler.lambda_handler",
            code=lambda_.Code.from_asset(os.path.join(BUILD_DIR, "api")),
            timeout=cdk.Duration.seconds(30),
            memory_size=256,
            environment=common_env,
            log_group=logs.LogGroup(
                self,
                "NextApiFunctionLogGroup",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=cdk.RemovalPolicy.DESTROY,
            ),
        )

        self.mcp_function = lambda_.Function(
            self,
            "NextMcpFunction",
            function_name=f"{config.PREFIX}-mcp",
            runtime=lambda_.Runtime.PYTHON_3_12,
            architecture=lambda_.Architecture.X86_64,
            handler="handler.lambda_handler",
            code=lambda_.Code.from_asset(os.path.join(BUILD_DIR, "mcp")),
            timeout=cdk.Duration.seconds(60),
            memory_size=512,
            environment=common_env,
            log_group=logs.LogGroup(
                self,
                "NextMcpFunctionLogGroup",
                retention=logs.RetentionDays.ONE_WEEK,
                removal_policy=cdk.RemovalPolicy.DESTROY,
            ),
        )

        for fn in (self.api_function, self.mcp_function):
            table.grant_read_write_data(fn)
            # On-demand site rebuilds: /api/admin/rebuild and MCP
            # trigger_rebuild. Scoped to the one project.
            fn.add_to_role_policy(
                iam.PolicyStatement(
                    actions=["codebuild:StartBuild"],
                    resources=[
                        f"arn:aws:codebuild:{config.REGION}:{config.ACCOUNT}:"
                        f"project/{config.PREFIX}-site-generator"
                    ],
                )
            )
            fn.add_to_role_policy(
                iam.PolicyStatement(
                    # dctech.events is verified at the domain level (SES
                    # DKIM), not per-address, so that's the identity ARN that
                    # actually gates ses:SendEmail regardless of which
                    # address under it FROM_EMAIL uses.
                    actions=["ses:SendEmail"],
                    resources=[
                        f"arn:aws:ses:{config.REGION}:{config.ACCOUNT}:identity/dctech.events"
                    ],
                )
            )
            fn.add_to_role_policy(
                iam.PolicyStatement(
                    # Magic-link emails, plus the newsletter opt-in on the
                    # submission form (create/get/update contact).
                    actions=[
                        "ses:ListContacts",
                        "ses:CreateContact",
                        "ses:GetContact",
                        "ses:UpdateContact",
                    ],
                    resources=[
                        f"arn:aws:ses:{config.REGION}:{config.ACCOUNT}:"
                        f"contact-list/{config.NEWSLETTER_CONTACT_LIST}"
                    ],
                )
            )
            # trigger_rebuild / POST /api/admin/rebuild (project name wired in
            # by the site-generator stack once it exists)
            fn.add_to_role_policy(
                iam.PolicyStatement(
                    actions=["codebuild:StartBuild"],
                    resources=[
                        f"arn:aws:codebuild:{self.region}:{self.account}:project/{config.PREFIX}-site-generator"
                    ],
                )
            )

        # Only the API Lambda ever touches magic-link tokens (issuing them on
        # /api/submit-link, verifying them on /api/submissions and
        # /api/corrections) — the MCP Lambda has no code path that calls
        # magic_link.py at all, so it never needed this. Previously granted
        # to both inside the loop above by accident, widening this key's
        # blast radius for no reason.
        self.submit_key.grant(self.api_function, "kms:GenerateMac", "kms:VerifyMac")
        # Defense in depth beyond the IAM grant above: an explicit statement
        # on the key's own resource policy naming exactly this role, so a
        # future IAM policy elsewhere that happens to grant kms:GenerateMac
        # broadly (e.g. a wildcard admin policy) still isn't enough on its
        # own to use this specific key — the key's own policy has to agree
        # too. The account-root statement CDK generates by default stays, so
        # normal key administration (rotation, console access) is unaffected.
        self.submit_key.add_to_resource_policy(
            iam.PolicyStatement(
                sid="RestrictMacOpsToSubmitLinkIssuerRole",
                effect=iam.Effect.ALLOW,
                principals=[iam.ArnPrincipal(self.api_function.role.role_arn)],
                actions=["kms:GenerateMac", "kms:VerifyMac"],
                resources=["*"],
            )
        )

        # prefs_key: generates (for /api/submit-link's preferences-link
        # request flow) and verifies (routes/preferences.py) here. No
        # matching add_to_resource_policy() statement for api_function the
        # way submit_key gets one, on purpose: prefs_key is a resource
        # physically owned by NextNewsletterStack (constructed there), so
        # mutating its policy from here would embed this stack's own role
        # ARN into a NextNewsletterStack resource — creating exactly the
        # dependency cycle NextNewsletterStack -> NextApiStack -> (via
        # prefs_key=newsletter.prefs_key in app.py) NextNewsletterStack
        # again, confirmed by `cdk synth` refusing to synthesize when this
        # was tried. The plain grant() below is sufficient on its own: a
        # CDK-created key's default policy already trusts account
        # identities, so IAM-side permission is all a grantee actually
        # needs. The one resource-policy restriction that *is* safe to add
        # lives in NextNewsletterStack instead, restricting sender_function
        # (same-stack as the key there, no cycle).
        prefs_key.grant(self.api_function, "kms:GenerateMac", "kms:VerifyMac")

        api = apigateway.RestApi(
            self,
            "NextApi",
            rest_api_name=f"{config.PREFIX}-api",
            description="next.dctech.events API",
            deploy_options=apigateway.StageOptions(
                stage_name=stage_name,
                metrics_enabled=True,
            ),
            default_cors_preflight_options=apigateway.CorsOptions(
                allow_origins=apigateway.Cors.ALL_ORIGINS,
                allow_methods=apigateway.Cors.ALL_METHODS,
                allow_headers=[
                    "Content-Type", "Authorization", "HX-Request", "HX-Trigger",
                    "HX-Trigger-Name", "HX-Target", "HX-Current-URL",
                ],
            ),
        )

        authorizer = apigateway.CognitoUserPoolsAuthorizer(
            self,
            "NextCognitoAuthorizer",
            cognito_user_pools=[user_pool],
            identity_source="method.request.header.Authorization",
        )
        authed = {
            "authorizer": authorizer,
            "authorization_type": apigateway.AuthorizationType.COGNITO,
        }

        integration = apigateway.LambdaIntegration(
            self.api_function, proxy=True, allow_test_invoke=False
        )

        # Public routes
        api.root.add_resource("health").add_method("GET", integration)
        api_res = api.root.add_resource("api")
        api_res.add_resource("events").add_method("GET", integration)
        api_res.add_resource("categories").add_method("GET", integration)

        # Event submission is deliberately unauthenticated at the gateway:
        # submitters authenticate with an emailed magic link that the Lambda
        # verifies itself (routes/submit.py). Attaching the Cognito authorizer
        # here would reject link-holders before Lambda ever sees the token.
        api_res.add_resource("submit-link").add_method("POST", integration)
        api_res.add_resource("submissions").add_method("POST", integration)

        # Same reasoning: correction submitters authenticate with the same
        # emailed magic link, and the public event read is a deliberately
        # narrow, unauthenticated endpoint (routes/corrections.py) so the
        # correction form has something to render without needing the
        # admins-only event detail route.
        api_res.add_resource("corrections").add_method("POST", integration)

        # Same reasoning again: a subscriber manages their category/region
        # newsletter filters via the same emailed magic-link pattern
        # (routes/preferences.py, purpose='prefs') rather than a Cognito
        # account, since a newsletter subscriber never has one.
        preferences_res = api_res.add_resource("preferences")
        preferences_res.add_method("GET", integration)
        preferences_res.add_method("POST", integration)

        public_res = api_res.add_resource("public")
        public_res.add_resource("events").add_resource("{guid}").add_method(
            "GET", integration)
        # Same public-read reasoning, for a recurring series (and optionally
        # one of its occurrences via ?date=) instead of an EVENT# record.
        public_res.add_resource("recurring").add_resource("{slug}").add_method(
            "GET", integration)

        # Authenticated JSON API
        api_res.add_resource("my-submissions").add_method("GET", integration, **authed)
        api_res.add_resource("admin").add_proxy(
            default_integration=integration,
            default_method_options=apigateway.MethodOptions(**authed),
            any_method=True,
        )

        # Authenticated HTMX routes
        submit = api.root.add_resource("submit")
        submit.add_method("GET", integration, **authed)
        submit.add_method("POST", integration, **authed)
        api.root.add_resource("my-submissions").add_method("GET", integration, **authed)
        admin = api.root.add_resource("admin")
        admin.add_method("ANY", integration, **authed)
        admin.add_proxy(
            default_integration=integration,
            default_method_options=apigateway.MethodOptions(**authed),
            any_method=True,
        )

        # MCP endpoint — IAM auth (trusted agents/Lambdas only, not end users)
        mcp_integration = apigateway.LambdaIntegration(
            self.mcp_function, proxy=True, allow_test_invoke=False
        )
        mcp_res = api.root.add_resource("mcp")
        mcp_res.add_method(
            "ANY", mcp_integration,
            authorization_type=apigateway.AuthorizationType.IAM,
        )
        mcp_res.add_proxy(
            default_integration=mcp_integration,
            default_method_options=apigateway.MethodOptions(
                authorization_type=apigateway.AuthorizationType.IAM
            ),
            any_method=True,
        )

        # Cognito authorizer rejections bypass Lambda entirely, so they have no
        # CORS headers by default; without one, the legitimate admin frontend
        # can't even read a 401 to show "please log in" (the request just
        # errors out as an opaque CORS failure). A literal '*' "fixed" that
        # but let any site's JS read these bodies too (they're just a fixed
        # "Unauthorized"/"Forbidden" string, but a wildcard is still the
        # wrong default) — reflect the caller's own Origin header instead of
        # a real allowlist: gateway response headers are static/VTL-mapped,
        # with no conditional logic available to check membership the way
        # handler.py's get_cors_origin() does for actual Lambda responses.
        api.add_gateway_response(
            "UnauthorizedGatewayResponse",
            type=apigateway.ResponseType.UNAUTHORIZED,
            response_headers={
                "Access-Control-Allow-Origin": "method.request.header.origin",
                "Access-Control-Allow-Headers": "'Content-Type,Authorization,HX-Request,HX-Trigger,HX-Trigger-Name,HX-Target,HX-Current-URL'",
            },
        )
        api.add_gateway_response(
            "AccessDeniedGatewayResponse",
            type=apigateway.ResponseType.ACCESS_DENIED,
            response_headers={
                "Access-Control-Allow-Origin": "method.request.header.origin",
                "Access-Control-Allow-Headers": "'Content-Type,Authorization,HX-Request,HX-Trigger,HX-Trigger-Name,HX-Target,HX-Current-URL'",
            },
        )

        self.api = api
        self.api_endpoint = api.url
        # Consumed by NextQaAgentStack — the QC agent reaches events only
        # through this endpoint.
        self.mcp_url = f"{api.url}mcp"

        cdk.CfnOutput(self, "NextApiEndpoint", value=api.url)
        cdk.CfnOutput(self, "NextMcpUrl", value=self.mcp_url)
        # The sole authentication factor for anonymous submission/correction
        # (magic_link.py's SUBMIT_KEY_ID) — surfaced here so the active key
        # is always one `aws cloudformation describe-stacks` away instead of
        # something only discoverable by grepping the deployed Lambda's
        # environment or trusting a possibly-stale note somewhere else (this
        # session found exactly that: a remembered key id that had drifted
        # from what was actually deployed).
        cdk.CfnOutput(self, "NextSubmitLinkKeyId", value=self.submit_key.key_id)
