"""NextSocialStack — credentials for cross-posting to social platforms.

Holds only Secrets Manager secrets, so rotating or re-populating social
credentials never rides along with an application deploy. Both secrets are
issued by the platforms themselves and cannot be generated by CDK: the
stack creates them with a placeholder shape and the real values are filled
in out-of-band (see the module docstring below for the commands).

Populate after the first deploy:

    aws secretsmanager put-secret-value \\
      --secret-id dctech-events-next/mastodon \\
      --secret-string '{"instance_url":"https://...","access_token":"..."}'

    aws secretsmanager put-secret-value \\
      --secret-id dctech-events-next/bluesky \\
      --secret-string '{"identifier":"dctech.events","app_password":"..."}'

Grant a consuming Lambda access with
``social.mastodon_secret.grant_read(fn)``.
"""
import json

import aws_cdk as cdk
from aws_cdk import aws_secretsmanager as secretsmanager
from constructs import Construct

import config


class NextSocialStack(cdk.Stack):
    def __init__(self, scope: Construct, construct_id: str, **kwargs) -> None:
        super().__init__(scope, construct_id, **kwargs)

        # RETAIN on both: the values are externally-issued credentials that
        # cannot be recovered from anywhere else in this app, so a stack
        # teardown must not take them with it.
        self.mastodon_secret = secretsmanager.Secret(
            self,
            "NextMastodonSecret",
            secret_name=f"{config.PREFIX}/mastodon",
            description=(
                "Mastodon instance URL and API access token for posting "
                "dctech.events updates"
            ),
            # CDK's default is a bare random string, which would break a
            # consumer that json.loads() the value. Seed the real key shape
            # instead so the placeholder parses before it is populated.
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template=json.dumps(
                    {"instance_url": "https://mastodon.social", "access_token": ""}
                ),
                generate_string_key="placeholder",
            ),
            removal_policy=cdk.RemovalPolicy.RETAIN,
        )

        self.bluesky_secret = secretsmanager.Secret(
            self,
            "NextBlueskySecret",
            secret_name=f"{config.PREFIX}/bluesky",
            description=(
                "Bluesky handle and app password for posting dctech.events "
                "updates"
            ),
            generate_secret_string=secretsmanager.SecretStringGenerator(
                secret_string_template=json.dumps(
                    {"identifier": "dctech.events", "app_password": ""}
                ),
                generate_string_key="placeholder",
            ),
            removal_policy=cdk.RemovalPolicy.RETAIN,
        )

        cdk.CfnOutput(
            self,
            "MastodonSecretArn",
            value=self.mastodon_secret.secret_arn,
            description="ARN of the Mastodon credential secret",
        )
        cdk.CfnOutput(
            self,
            "BlueskySecretArn",
            value=self.bluesky_secret.secret_arn,
            description="ARN of the Bluesky credential secret",
        )
