"""When each event was first recorded, for /just-added/.

The site's own event data says nothing about when a listing appeared — an
event added this morning and one added in March are indistinguishable in
`_data/all_events.json`. The only record is `createdAt` on the table's EVENT#
rows, which the site exporter writes out as `_data/added_at.json`.

Two lookups into the same answer, because event identity is not consistent
across the two sides: iCal events share one guid with the site's data, but
submitted events are keyed `EVENT#<8 hex>` in the table while calgen
recomputes a 32-char content hash for them (next_dctech_events-p8o), so those
match only on (date, title). Where both hit, the guid wins — it is the
stronger identity, and a title collision between two groups on the same night
is entirely possible.

`_title_key` here must stay byte-identical to the exporter's and to
updates_publisher's, or the join quietly stops matching and /just-added/
empties out without erroring.
"""
import json
import os

ADDED_AT_FILE = os.path.join('_data', 'added_at.json')


def _title_key(date_str, title):
    return f"{date_str}|{' '.join(str(title or '').split()).casefold()}"


def get_added_at_index():
    """(by_guid, by_title), or ({}, {}) when the export has not run."""
    try:
        with open(ADDED_AT_FILE, 'r', encoding='utf-8') as f:
            data = json.load(f) or {}
    except (OSError, ValueError):
        return {}, {}
    return data.get('by_guid') or {}, data.get('by_title') or {}


def added_at(event, by_guid, by_title):
    """ISO-8601 timestamp this event was first recorded, or None."""
    guid = event.get('guid')
    if guid and guid in by_guid:
        return by_guid[guid]
    return by_title.get(_title_key(event.get('date'), event.get('title')))


def added_on(event, by_guid, by_title):
    """Just the date part — what /just-added/ groups by.

    createdAt is ISO-8601 UTC ('2026-08-13T00:27:22Z'), so the first ten
    characters are the date and string comparison on them is a correct day
    comparison.
    """
    stamp = added_at(event, by_guid, by_title)
    return stamp[:10] if stamp else None


def group_by_added_date(events, limit_days=None):
    """Events bucketed by the day they were recorded, newest day first.

    Events with no recorded date are omitted rather than lumped into a
    guessed bucket: recurring occurrences are generated by calgen and have no
    EVENT# row at all, so "unknown" here is common and not an error.
    """
    by_guid, by_title = get_added_at_index()
    if not by_guid and not by_title:
        return []

    days = {}
    for event in events:
        day = added_on(event, by_guid, by_title)
        if not day:
            continue
        days.setdefault(day, []).append(event)

    ordered = sorted(days.items(), reverse=True)
    if limit_days:
        ordered = ordered[:limit_days]

    return [{
        'date': day,
        'anchor': day,
        'count': len(items),
        'events': sorted(items, key=lambda e: (e.get('date', ''), e.get('time') or '')),
    } for day, items in ordered]
